image: python:3.6.10-slim

stages:    
    - test
    - deploy

test:
    stage: test
    script:         
        - pip install -r orchestrator/requirements.txt
        - python orchestrator/test.py

build_image:
    stage: test
    tags: 
        - build_docker
    script:
        - echo "$REGI_PASS" | docker login -u "$REGI_USER" --password-stdin
        - docker build -t icair/dtnaas:orchestrator .
        - docker pull icair/dtnaas:agent
        - mkdir data; echo "hello_world!" > data/hello_world
        - docker run --rm -d --name=daas_agent --network="host" -v "$(pwd)"/data:/data icair/dtnaas:agent
        - docker run -t --network="host" icair/dtnaas:orchestrator orchestrator/test.py
        - docker push icair/dtnaas:orchestrator
    after_script:
        - docker stop daas_agent

deploy:
    stage: deploy
    tags: 
        - deploy_orchestrator
    before_script:
        - docker stop daas_orchestrator || true
    script:
        - docker run -d --rm --name=daas_orchestrator --network="host" icair/dtnaas:orchestrator        