version: "3.8"
networks:
  orchestrator_net:
services:
  notebook:
    #image: jupyter/scipy-notebook
    # need to build notebook so we can copy the orchestrator client lib
    build: ./notebook
    ports:
      - "8888:8888"
    networks:
      - orchestrator_net
    volumes:
      - ./db:/orchestrator/db
      # jovyan is the default non-root user for jupyter
      - ./work:/home/jovyan/work
      # debug - allows kernel restarts to update library code
      #- ./notebook/dtn_orchestrator:/opt/conda/lib/python3.9/dtn_orchestrator

  orchestrator:
    build: ./
    # don't make the orchestrator available outside of this net
    #ports:
    #  - "5000:5000"
    networks:
      - orchestrator_net
    volumes:
      - ./db:/orchestrator/db
