"""empty message

Revision ID: 0180febef39b
Revises: 9cbcc15c6b24
Create Date: 2020-05-09 12:30:19.571269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0180febef39b'
down_revision = '9cbcc15c6b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer', 'num_workers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transfer', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transfer', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('transfer', 'file_sizes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('file_sizes', sa.INTEGER(), nullable=False))
    op.alter_column('transfer', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transfer', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transfer', 'num_workers',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
