"""added worker_types

Revision ID: 15df1cfe4d0f
Revises: b83fe17e0901
Create Date: 2020-05-19 14:55:53.423348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15df1cfe4d0f'
down_revision = 'b83fe17e0901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WorkerType',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('worker_type_id', 'WorkerType', ['worker_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.drop_constraint('worker_type_id', type_='foreignkey')
        batch_op.drop_column('worker_type_id')

    op.drop_table('WorkerType')
    # ### end Alembic commands ###
