"""empty message

Revision ID: 302c9af6a6c9
Revises: b78e123b43ba
Create Date: 2020-05-08 19:32:41.098505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302c9af6a6c9'
down_revision = 'b78e123b43ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('file_size', sa.Integer(), nullable=False))
    op.drop_column('transfer', 'file_sizes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('file_sizes', sa.INTEGER(), nullable=False))
    op.drop_column('transfer', 'file_size')
    # ### end Alembic commands ###
