"""empty message

Revision ID: 3368cd87c6fc
Revises: b23d311e254d
Create Date: 2020-05-09 12:33:50.905161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3368cd87c6fc'
down_revision = 'b23d311e254d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.alter_column('num_workers',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('file_sizes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_sizes', sa.INTEGER(), nullable=False))
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('num_workers',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
