"""empty message

Revision ID: 46c0bc74f542
Revises: 8db9e2daf8ae
Create Date: 2020-05-09 12:28:41.263275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c0bc74f542'
down_revision = '8db9e2daf8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('file_size', sa.Integer(), nullable=True))
    op.alter_column('transfer', 'num_workers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transfer', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transfer', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('transfer', 'file_sizes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('file_sizes', sa.INTEGER(), nullable=False))
    op.alter_column('transfer', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transfer', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transfer', 'num_workers',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transfer', 'file_size')
    # ### end Alembic commands ###
