"""empty message

Revision ID: 7f9dc6226b73
Revises: 9fbddc24e8aa
Create Date: 2020-03-26 20:05:57.625203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f9dc6226b73'
down_revision = '9fbddc24e8aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DTN',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('man_addr', sa.String(length=15), nullable=False),
    sa.Column('data_addr', sa.String(length=15), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_addr'),
    sa.UniqueConstraint('man_addr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DTN')
    # ### end Alembic commands ###
