"""empty message

Revision ID: 811826ac2367
Revises: 
Create Date: 2020-03-26 21:00:11.524641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811826ac2367'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DTN',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('man_addr', sa.String(length=80), nullable=True),
    sa.Column('data_addr', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DTN')
    # ### end Alembic commands ###
