"""empty message

Revision ID: 8db9e2daf8ae
Revises: 3bd7b557d144
Create Date: 2020-05-08 19:46:28.435985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db9e2daf8ae'
down_revision = '3bd7b557d144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transfer', 'num_workers',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer', 'num_workers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transfer', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
