"""empty message

Revision ID: 9fbddc24e8aa
Revises: 
Create Date: 2020-03-20 15:11:53.577260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fbddc24e8aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DTN',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('man_ip', sa.String(length=15), nullable=False),
    sa.Column('data_ip', sa.String(length=15), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_ip'),
    sa.UniqueConstraint('man_ip')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DTN')
    # ### end Alembic commands ###
