"""empty message

Revision ID: b78e123b43ba
Revises: 811826ac2367
Create Date: 2020-05-08 18:30:57.579440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78e123b43ba'
down_revision = '811826ac2367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('file_sizes', sa.Integer(), nullable=False),
    sa.Column('num_workers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['DTN.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['DTN.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer')
    # ### end Alembic commands ###
