"""added tool

Revision ID: b83fe17e0901
Revises: cf60b4be72bb
Create Date: 2020-05-14 14:35:47.753750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83fe17e0901'
down_revision = 'cf60b4be72bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.drop_column('tool')

    # ### end Alembic commands ###
