"""added latency

Revision ID: cf60b4be72bb
Revises: f6c6201ea0f1
Create Date: 2020-05-12 22:35:56.504676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf60b4be72bb'
down_revision = 'f6c6201ea0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latency', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.drop_column('latency')

    # ### end Alembic commands ###
