"""empty message

Revision ID: eb5a39daa38b
Revises: 877863150da0
Create Date: 2020-05-09 12:29:27.856418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5a39daa38b'
down_revision = '877863150da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer', 'num_workers',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transfer', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transfer', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('transfer', 'file_sizes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('file_sizes', sa.INTEGER(), nullable=False))
    op.alter_column('transfer', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transfer', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transfer', 'num_workers',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
