"""added num_files

Revision ID: f6c6201ea0f1
Revises: 3368cd87c6fc
Create Date: 2020-05-12 15:55:52.822264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c6201ea0f1'
down_revision = '3368cd87c6fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_files', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer', schema=None) as batch_op:
        batch_op.drop_column('num_files')

    # ### end Alembic commands ###
